import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Quicksand } from 'next/font/google'
 
const roboto = Quicksand({
  weight: '400',
  subsets: ['latin'],
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
